POST http://localhost:8080/test/calc
Content-Type: application/json
api_key:495ed4a3-4e4c-4977-9aad-ef999aea1060

{
  "num1": 5,
  "num2": 8,
  "operationType": "MULT"
}

###

POST http://localhost:8080/test/calc
Content-Type: application/json
api_key: 495ed4a3-4e4c-4977-9aad-ef999aea1060

{
  "num1": 11,
  "num2": 5,
  "operationType": "SUM"
}

###

POST http://localhost:8080/test/calc
Content-Type: application/json

{
  "num1": 6,
  "num2": 3,
  "operationType": "SUM"
}

###


POST http://localhost:8080/test/calc
Content-Type: application/json

{
  "num1": 31,
  "num2": 5,
  "operationType": "DIV"
}

###
GET http://localhost:8080/test/history
api_key:495ed4a3-4e4c-4977-9aad-ef999aea1060

###

GET http://localhost:8080/test/test
Content-Type: application/json
api_key:495ed4a3-4e4c-4977-9aad-ef999aea1060

{
  "operationType": "SUM"
}

###

POST http://localhost:8080/user/reg
Content-Type: application/json

{
  "name": "name1",
  "login": "login1",
  "password": "password1"
}

###

POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "name": "name1",
  "login": "login1",
  "password": "password1"
}